### ISSUE TITLE
fetchUserName() and java.io.FileNotFoundException

### ISSUE THREAD

**Issue by slavkoder** [thiagolocatelli/android-instagram-oauth#2]
Hello, 

I'm trying to use the library and I found a bug in fetchUserName() method - it fails with FileNotFoundException. However, it's easy to fix, just remove the line urlConnection.setDoOutput(true); from the method, because it forces POST request instead of GET. 

Thank you for great job, the lib is of great help for me.

Best regards,
Slava Panasenko

**Comment by thiagolocatelli** [comment]
Thanks! you can actually submit a pull request and I will approve it with the code change.

**Comment by Testuser36** [comment]
Not working in my case.
Still getting 
```
W/System.err: java.io.FileNotFoundException: [(https://api.instagram.com/oauth/access_token)]
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:207)
W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
W/System.err:     at shared.InstagramApp$3.run(InstagramApp.java:145)
```

`W/System.err:     at shared.InstagramApp$3.run(InstagramApp.java:145)` ::  String response = Util.streamToString(urlConnection
                            .getInputStream());

**Comment by pratikbutani** [comment]
Any Solution?
